### ISSUE TITLE
I am trying to start Ansible tower on Ubuntu 16.04 hosted in a virtual box, but getting the following error while executing vagrant up

### ISSUE THREAD

**Issue by d4rk9i8t** [madhuakula/security-automation-with-ansible-2#1]
canon@canon:~/ansible-tower-setup-3.4.1-1$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ansible/tower' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "b816d870-6c05-489b-8413-90b25bcee468", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

**Comment by madhuakula** [comment]
Hello @d4rk9i8t 

Looks like it has some VirtualBox (or) vagrant issue.

* Also checkout the updated way to setup the Ansible Tower at https://docs.ansible.com/ansible-tower/latest/html/quickinstall/index.html
* Now we also have open source version of tower available as AWX, if you prefer (or) want to try out https://github.com/ansible/awx/blob/devel/INSTALL.md
